### PR TITLE
Displaying current data when on today's date

### LINKED ISSUE #157: Update Map.js to reflect current data
Update map.js to reflect current up-to-date data instead of 12:00 PM

Maybe include a time picker as well?

### LINKED ISSUE #213: Find me button on fire page
Add the find me button to the map on the fire page

### PR DESCRIPTION
**Pull request by abijeet-dhillon**
## In this PR:

- Changed the django view for station data to either show the latest data or show the data for a selected date. This change made the dashboard slow  quite slow in displaying data so I also changed the view to filter for station data as well, this made a huge difference in time taken to show the data once a station/date was clicked and the speed is as quick as it was before.

- Basically, when the user is on "Today", the dashboard displays the most recent data. When the user selects a date that is not "Today", the dashboard shows the data for that day at 12pm.

- Also added implementation of find me button on fire page.

Closes #157 #213

### CODE REVIEW

**Review by robertyac — DISMISSED** [review]
Works great for the weather page but the fire page all the data is 0 because I'm assuming most fire data is only collected once at 12:00pm. Is it possible to make the fire page be on 12:00pm?

**Comment by abijeet-dhillon** [comment]
> Works great for the weather page but the fire page all the data is 0 because I'm assuming most fire data is only collected once at 12:00pm. Is it possible to make the fire page be on 12:00pm?

Done, that was an oversight on my end, good catch!

**Comment by robertyac** [comment]
are you getting this bug for the wind gust widget on yours? it doesn't seem to be showing the gust bar and the "km/hr"
image

**Comment by abijeet-dhillon** [comment]
> are you getting this bug for the wind gust widget on yours? it doesn't seem to be showing the gust bar and the "km/hr" image

I checked on the main branch and it doesn't show it there either.

**Comment by robertyac** [comment]
Odd this is my main: 
image

**Comment by abijeet-dhillon** [comment]
> Odd this is my main: image

Fixed it, I accidentally deleted the wind gust code because it was duplicated. Should be good now.

**Review by Davis245 — APPROVED** [review]
LGTM

**Review by robertyac — APPROVED** [review]
Nice work this is a game changer

**Pull request merged**
