### PR TITLE
Connected weather_stationdata database with map, data picker, and home page.

### LINKED ISSUE #70: Data updates based on Station Selected on Map
#9

### PR DESCRIPTION
**Pull request by abijeet-dhillon**
Connected the weather_stationdata database with the map, data picker, and home page. The current home page is now fully functional in terms of displaying data. This includes:

- **Connecting The Date Picker To The Rest Of The Home Page**
  The date picker is now functional and should display different data on different dates.

- **Viewing Different Data From Different Dates**
  Upon loading the page, you won't see any data since it is set to today and today's data isn't loaded on the database (use March 5th, 2024 or earlier). When you change the date using the date picker, the station data is automatically updated and displays the new information for the currently selected station. Data which is null is displayed as "N/A".

- **N/A Values**
  Each time the user changes the date on the date picker or clicks somewhere on the map, the data fields on the right column (widgets) are reset to "N/A" and then updated with data. This ensures that previous data is not "lingering" and gives the user a more accurate display of the data.

Closes #70

### CODE REVIEW

**Comment by robertyac** [comment]
something isn't working for me?

https://github.com/carsondrobe/Fellas/assets/112982183/47b9a225-7fe7-4b1a-8140-cff632e04faf

**Comment by robertyac** [comment]
Maybe it's because of the new widget I put?

**Comment by robertyac** [comment]
I made sure to spam pull but this is what seems to be going on:

Its sending a GET request but not returning any data:
```
[08/Mar/2024 00:50:03] "GET /weather_stations_information/ HTTP/1.1" 200 47163
Not Found: /station_data/
```

**Comment by abijeet-dhillon** [comment]
> something isn't working for me?
> 
>  Screen.Recording.2024-03-07.at.4.29.17.PM.mov

@robertyac 

I'm not sure why it's doing that. Are there any error messages being logged to the console or printed in the terminal? Also, did it work for a bit then stop working or did it not work upon start up?

**Review by robertyac — COMMENTED** [review]
This is what I'm getting: 

 I tried this out again and I updated the database (didn't commit that) and it seems like it works for **today** but not any other day in the past.

```
 raise exceptions.ValidationError(
django.core.exceptions.ValidationError: ['“3/3/2024 12:00:00” value has an invalid format. It must be in YYYY-MM-DD HH:MM[:ss[.uuuuuu]][TZ] format.']
[08/Mar/2024 01:52:24] "GET /station_data/?datetime=3/3/2024%2012:00:00 HTTP/1.1" 500 128384
```

**Review by cmcahoon01 — CHANGES_REQUESTED** [review]
image
I am only getting N/A for the data

**Comment by abijeet-dhillon** [comment]
> This is what I'm getting:
> 
> I tried this out again and I updated the database (didn't commit that) and it seems like it works for **today** but not any other day in the past.
> 
> ```
>  raise exceptions.ValidationError(
> django.core.exceptions.ValidationError: ['“3/3/2024 12:00:00” value has an invalid format. It must be in YYYY-MM-DD HH:MM[:ss[.uuuuuu]][TZ] format.']
> [08/Mar/2024 01:52:24] "GET /station_data/?datetime=3/3/2024%2012:00:00 HTTP/1.1" 500 128384
> ```

Ah I see, the format of the datetime is wrong, which is weird since on my computer, it is requesting information with this get request:

[07/Mar/2024 18:00:15] "GET /station_data/?datetime=2024-03-07%2012:00:00 HTTP/1.1" 200 221444

Maybe try pulling and retrying? I am looking into it.

**Comment by abijeet-dhillon** [comment]
@robertyac  @cmcahoon01 

Try pulling the newest commit and running it. Lmk if the issues persist.

**Review by cmcahoon01 — APPROVED** [review]
Works correctly for me now.
I noticed a few of the stations are still N/A sometimes, but I assume that has to do with the dataset not this PR

**Comment by abijeet-dhillon** [comment]
> Works correctly for me now. I noticed a few of the stations are still N/A sometimes, but I assume that has to do with the dataset not this PR

Great! And yeah it's to do with the dataset.

**Comment by robertyac** [comment]
I checked again and it works for today but no past dates...

Screenshot 2024-03-07 at 6 32 49 PM
Screenshot 2024-03-07 at 6 33 28 PM

**Review by cmcahoon01 — DISMISSED** [review]
When clicking on a blank part of the map, the weather station is un-selected, and all data goes to N/A. Should be changed so clicking on an empty part of the map does nothing.

**Review by Davis245 — APPROVED** [review]
LGTM

**Comment by abijeet-dhillon** [comment]
> When clicking on a blank part of the map, the weather station is un-selected, and all data goes to N/A. Should be changed so clicking on an empty part of the map does nothing.

Fixed.

**Review by carsondrobe — APPROVED** [review]
She Works

**Review by robertyac — APPROVED** [review]
LGTM works now for me

**Pull request merged**
