### PR TITLE
Humidity widget

### LINKED ISSUE #54: Create humidity widget

### LINKED ISSUE #55: Add logic to humidity widget

### PR DESCRIPTION
**Pull request by robertyac**
Created a humidity widget using vanilla JavaScript to create a semi-circle progress bar. It creates SVG elements and manipulates them directly using the DOM API.

https://github.com/carsondrobe/Fellas/assets/112982183/de0bbbbe-729b-48f3-b68b-005fb40fb381

Note: we can do a bulk issue later to change colours just chose a random decentish looking blue.

closes #54

### CODE REVIEW

**Comment by Davis245** [comment]
What's the plan for creating tests for these widgets?

**Comment by robertyac** [comment]
#141

**Review by Davis245 — APPROVED** [review]
Looks good.

**Comment by robertyac** [comment]
That blue was an eyesore here is a better temp colour just to be more consistent for the time being 😭

Screenshot 2024-03-17 at 8 33 08 PM

**Comment by robertyac** [comment]
Updated with Qunit tests about 100% coverage all tests passing. 
`npm test`

Using Istanbul (nyc) for coverage 
`npm run test:coverage`

I don't know you might have to install some packages to run these tests?

Screenshot 2024-03-18 at 1 58 33 PM

**Review by carsondrobe — APPROVED** [review]
LGMT Tests passed on my end

**Pull request merged**
