### PR TITLE
Added max date to be today

### LINKED ISSUE #218: dont allow date selector on future dates
Prevent users from selecting future dates in the date picker.

### PR DESCRIPTION
**Pull request by Davis245**
Set the maximum date to be today if the user selects a date in the future, today's date will be selected.

Closes #218

### CODE REVIEW

**Review by carsondrobe — APPROVED** [review]
Perfect, good UI

**Review by abijeet-dhillon — CHANGES_REQUESTED** [review]
Looks good but I found a bug.

When the user is on a date that is not today, if the user clicks the clear button on the calendar it says invalid date. Then if the user clicks the toggle to switch pages to fire/weather, the dashboard changes to the respective page but the map doesn't load and it defaults to today's date. If the user tries to change the date to an earlier date, the map still isn't loading.

Maybe we can delete the clear date button on the calendar and just keep the today button?

**Comment by Davis245** [comment]
So there are two options:

1. Remove the clear button. This only works on Webkit-based browsers.
2. Set the date to the previous date when the clear button is pressed. This would make the clear button do nothing.

Also for context, Safari does not have a clear button nor a today button, Chrome has both a clear and today button, and Firefox only has a clear button.

**Comment by abijeet-dhillon** [comment]
> So there are two options:
> 
> 1. Remove the clear button. This only works on Webkit-based browsers.
> 2. Set the date to the previous date when the clear button is pressed. This would make the clear button do nothing.
> 
> Also for context, Safari does not have a clear button nor a today button, Chrome has both a clear and today button, and Firefox only has a clear button.


Ohhhh I see, I'm good with either option. Whichever is quicker/easiest to implement tbh.

**Comment by Davis245** [comment]
I implemented the second option in the last commit "Disabled the clear button".

**Pull request merged**
