### PR TITLE
112 fix fire widgets

### LINKED ISSUE #112: Fix fire widgets

### PR DESCRIPTION
**Pull request by Davis245**
Fixed fire widget merging errors:
      - removed repeated css code
      - renamed js variables and css/html ids to be unique and more detailed
      - edited pixel values for the arrows so they line up correctly again
      - made drought code title take up two lines so all the axes are at the same height
      - increased the margin below the moisture codes title's
      - decreased the margin below the fire danger rating title

Closes #112

### CODE REVIEW

**Review by cmcahoon01 — COMMENTED** [review]
image

Is this what the fire page is supposed to look like?

**Comment by cmcahoon01** [comment]
Never mind I just saw your other PR

**Review by cmcahoon01 — APPROVED** [review]
good stuff

**Comment by Davis245** [comment]
Ya had to change the design of this page due to not enough vertical space.

**Review by robertyac — APPROVED** [review]
Nice, looks goos hopefully now it's not too much of a pain to connect to the database.

**Pull request merged**
