### PR TITLE
109 organize fire widgets

### LINKED ISSUE #109: Organize fire widgets

### PR DESCRIPTION
**Pull request by Davis245**
Screenshot 2024-03-09 at 1 39 42 PM
The indexes card will be expanded to fill up the entire empty space once those visualizations are created, because the size of the card will depend on the size of the visualizations.
Closes #109

### CODE REVIEW

**Comment by cmcahoon01** [comment]
What are Indexes?

**Comment by Davis245** [comment]
The indexes are initial spread index, the buildup index, and the fire weather index. My plan is to create the indexes card similar to the moisture codes, but stack the widgets inside the card vertically instead of horizontally.

**Review by robertyac — APPROVED** [review]
Looks good I like that they are grouped together

**Review by abijeet-dhillon — APPROVED** [review]
LGTM

**Pull request merged**
