### PR TITLE
Created map.js tests and restructured map.js file.

### LINKED ISSUE #138: Create JS tests for map.js file.
Implemented tests using JEST as a testing framework since that is one of the frameworks which lets you mock Leaflet. Due to most of the code in the map.js file working to update the map, it isn't feasible/worthwhile to mock and test all of those functions since we can actively see their changes displayed on the map/dashboard.

### LINKED ISSUE #147: Clean up map.js file to be more readable, structured, and less repetitive.

### PR DESCRIPTION
**Pull request by abijeet-dhillon**
##In this PR:

-Implemented tests using JEST as a testing framework since that is one of the frameworks which lets you mock Leaflet. Due to most of the code in the map.js file working to update the map, it isn't feasible/worthwhile to mock and test all of those functions since we can actively see their changes displayed on the map/dashboard.

-Cleaned up the map.js file.

-Got rid of some of the console errors appearing.

Nothing drastic was changed.

Closes #138 #147

### CODE REVIEW

**Review by carsondrobe — APPROVED** [review]
Works for me!

**Review by robertyac — CHANGES_REQUESTED** [review]
All your tests are passing for me! perfect. Want to run a merge from main and then I can add your tests to the CI workflow? or if you would like to add them that would be good! just let me know 👍

**Review by abijeet-dhillon — COMMENTED** [review]
Ran a merge, would you mind adding my tests to the CI workflow? I'd really appreciate it! @robertyac

**Comment by abijeet-dhillon** [comment]
> Ran a merge, would you mind adding my tests to the CI workflow? I'd really appreciate it! @robertyac

Done!

**Review by robertyac — APPROVED** [review]
Looks good now that you added it to the CI

**Pull request merged**
