### PR TITLE
116 fwi widget

### LINKED ISSUE #116: FWI widget

### PR DESCRIPTION
**Pull request by Davis245**
- Added the Fire Weather Index widget.
- updated the buildup index and drought code scales as they were incorrect.
- Updated the fire page layout to include two columns with rows inside instead of two rows with columns inside.

Closes #116

### CODE REVIEW

**Review by robertyac — DISMISSED** [review]
Looking a little glitched out on my end with the numbers:

Screenshot 2024-03-17 at 3 47 16 PM

**Review by carsondrobe — APPROVED** [review]
Works good on my end!

**Comment by carsondrobe** [comment]
Screenshot 2024-03-17 at 4 14 27 PM
LGTM

**Comment by robertyac** [comment]
It's probably just me then, someone else can check on theirs

**Pull request merged**
