### PR TITLE
Add profile page

### LINKED ISSUE #169: Add profile page or profile modal
User should be able to update some of their information for their account.

### PR DESCRIPTION
**Pull request by robertyac**
Added profile page, connected to db and styled for mobile & desktop.

Draft as I need to write tests. Functionality done though.

Screenshot 2024-03-24 at 11 42 27 PM
(zoomed out to see everything in one ss)

Notes: 
- if a feedback item has been marked as addressed it won't show. 
- Only normal users can see this page (since admins have access to the Django admin page)
- username is read only (I can remove this field if need be or if we want to allow a user name to be updatable then can keep)

### CODE REVIEW

**Comment by robertyac** [comment]
Additional notes:

- Only normal users can see this page (since admins have access to the Django admin page)
- username is read only (I can remove this field if need be or if we want to allow a user name to be updatable then can keep)

**Comment by robertyac** [comment]
Will probably change the white border to be wrapped around the whole card. Will experiment.

**Comment by carsondrobe** [comment]
Looks beautiful

**Comment by robertyac** [comment]
Updated design:
Screenshot 2024-03-25 at 2 14 40 PM

**Review by abijeet-dhillon — APPROVED** [review]
Awesome, the design looks great to me!

**Review by Davis245 — APPROVED** [review]
Looks good. Well done.

**Pull request merged**
