### PR TITLE
Dark Mode

### LINKED ISSUE #106: Create dark mode alternative

### PR DESCRIPTION
**Pull request by cmcahoon01**
Please give feedback on colors and formatting.

image

image

### CODE REVIEW

**Review by robertyac — CHANGES_REQUESTED** [review]
Awesome looks a lot better imo than the light mode! 

If possible and if it's easy maybe take a look at changing the station icon colour on the map. I find it to be a little too much black in that case.

**Comment by Davis245** [comment]
Looks good. I like the choice of colours! 

I agree with Rob there is a lot of black on the map. I think either changing the colour of the weather stations to something light or even just use the light map.

**Comment by cmcahoon01** [comment]
How do we like this?

image

I can also go back to the old icon but with a light color

**Comment by robertyac** [comment]
that looks a little better, how does it look if you change the original icons colours?

**Comment by cmcahoon01** [comment]
> that looks a little better, how does it look if you change the original icons colours?

They aren't svgs its harder to edit

**Comment by robertyac** [comment]
Any good ones from here we like? (svgs)
[icons](https://www.svgrepo.com/vectors/weather-station/)
[icons 2](https://thenounproject.com/browse/icons/term/weather-station/)
[icons 3](https://iconscout.com/icons/weather-station)

**Comment by cmcahoon01** [comment]
> Any good ones from here we like? 

Something to note is taller looks better in our map

I like this one:
image

**Review by abijeet-dhillon — COMMENTED** [review]
Pretty sure it's an issue on my part, the dashboard looks like the following when I try loading it up (I've tried pulling the branch and clearing the browser cache as well):

Screenshot (137)

**Comment by cmcahoon01** [comment]
image

**Review by robertyac — APPROVED** [review]
Looks good and works!

**Review by Davis245 — APPROVED** [review]
LGTM. I really like the final icon used on the map.

**Review by robertyac — APPROVED** [review]
Nice work

**Pull request merged**
