### PR TITLE
combine wind speed and gust, delete unused image

### LINKED ISSUE #155: Merge Wind Gust Widget into Wind Speed
Create a widget with logic for wind gust

### PR DESCRIPTION
**Pull request by carsondrobe**
I combined the wind speed and gust widgets into one. Attempted to combine the two into the circle but failed to do so. The text for the wind gust can change colour based on extreme wind gusts. I may revisit the circle challenge at another time.

Now we can get a better idea as to how we can get the 2x3 column sorted out on the weather page. 

Also deleted an old static image of a BC Map we used in the initial templates.

### CODE REVIEW

**Comment by carsondrobe** [comment]
Screenshot 2024-03-30 at 9 53 53 PM

No idea why this is happening

**Comment by carsondrobe** [comment]
Screenshot 2024-03-30 at 10 13 59 PM

**Comment by carsondrobe** [comment]
Updated red text for wind gust at +40 km/h

**Comment by carsondrobe** [comment]
Screenshot 2024-03-31 at 12 01 00 PM

Got the extended circle for wind gust. It was confusing to tell what the different colors meant so i also changed the text colors to provide some user hints. Now it doesn't change color based on wind speeds though. Please provide some feedback on which is better

**Comment by robertyac** [comment]
I like the looks of the second one good stuff!

**Review by robertyac — APPROVED** [review]
Awesome looks and works great! Maybe experiment with something like just having the words `Gust: 24 km/hr` at the bottom so it fits neatly on one line?

**Review by abijeet-dhillon — APPROVED** [review]
LGTM, I like that you combined them into one card! Also, I second what Robert said with experimenting with only "Gust: X km/h", would look a bit cleaner.

**Comment by Davis245** [comment]
If you do decide on using the format Gust: X km/h to put it on one line, see if Gusting would fit on one line. Gusting would make more sense in this situation.

**Pull request merged**
