### PR TITLE
Added user phone number and redid login/register flow

### LINKED ISSUE #166: Add User phone number to registration & model
Need to add a field for user phone number for the alerts function with twillio. It will be a field in the log in sequence as well.

### LINKED ISSUE #168: Add user type to login
Implement existing database architecture to support user type on registration. This adds it to the user profile table.

### LINKED ISSUE #171: Update JS error handling on login/register
Update the error handling using JS to make it look better instead of a popup. (use tooltips or similar)

### PR DESCRIPTION
**Pull request by robertyac**
- redid login and register modals layouts
- added phone number field to `userProfile` model
- added phone number validation (E.164 validation) used for twillio
- added dark mode for phone number field

https://github.com/carsondrobe/Fellas/assets/112982183/59c95eab-17c6-4074-aab1-e96120f2290b

### CODE REVIEW

**Comment by robertyac** [comment]
Tried adding the needed css and javascript for the phone number field at the bottom of `modal.html` to external documents but it wouldn't work for me.

**Comment by robertyac** [comment]
Updated client side validation for both forms:
Screenshot 2024-03-21 at 8 06 53 PM
Screenshot 2024-03-21 at 8 07 03 PM

**Review by carsondrobe — APPROVED** [review]
Good work!

**Review by abijeet-dhillon — APPROVED** [review]
Works good on my end, nice!

**Pull request merged**
