### PR TITLE
Finalizing widget layout and implementation of mobile view.

### LINKED ISSUE #88: Adapt layout to look good on mobile size.
Should not be started until most of the widgets are done to avoid working twice

### LINKED ISSUE #156: Remove snow quality widget
all values are 0 in the database. Look into if we really need this widget or not

### PR DESCRIPTION
**Pull request by cmcahoon01**
To pull it up on your phone, do 
`runserver 192.168.1.68:8000`
where 192.168.1.68 is your private ip of your computer. (You can cmd `ifconfig` or `ipconfig` to find your private ip)
then go on your phone and type 192.168.1.68(your ip) into the url, and it should load

To host on a private ip, meaning you can access it from other networks, you'll need a few more steps. I can walk you through it

### CODE REVIEW

**Comment by cmcahoon01** [comment]
Some of the automated tests failed because of path issues:
> Failed to load file website/tests/robert/wind_directionTest.js

> Error: Cannot find module '../../static/wind_direction.js'

I'll look into it. The wind direction widget still works as expected, so its likely a simple fix

**Comment by cmcahoon01** [comment]
image
image
image

**Comment by carsondrobe** [comment]
This looks good, looks like some failing tests.
Love the mobile view!

**Comment by robertyac** [comment]
merge conflicts ahoy, will review once fixed

**Comment by cmcahoon01** [comment]
I'm not sure if registration is working. Could someone test it?

**Review by robertyac — CHANGES_REQUESTED** [review]
Awesome looks a lot better already!

Is it possible to take another look at the spacing and widget sizes before merging?
Screenshot 2024-04-04 at 8 38 57 PM

Vs the heights and spacing (like the precipitation widget) from main: 
Screenshot 2024-04-04 at 8 41 52 PM

**Comment by robertyac** [comment]
All the javascript client side validation is broken too

**Comment by robertyac** [comment]
Screenshot 2024-04-04 at 8 48 14 PM

**Comment by cmcahoon01** [comment]
How do you like this?
image

**Review by robertyac — CHANGES_REQUESTED** [review]
Nice work! layout is looking a lot more uniform now. By chance would it be possible to make the widgets a little bigger? seems to be a lot of dead space/margin around the widgets.

Try getting all the titles in one line instead of them wrapping into a new line?

Also the snow number value is overlapping the container a little:
Screenshot 2024-04-04 at 9 53 57 PM

**Comment by cmcahoon01** [comment]
Thoughts on this?
image

**Comment by carsondrobe** [comment]
i think the previous version looks better because all the widgets were the same size, both are fine though.

**Comment by carsondrobe** [comment]
Screenshot 2024-04-06 at 2 06 13 PM

This is how the fire page looks on my macbook screen width...

**Comment by carsondrobe** [comment]
> Screenshot 2024-04-06 at 2 06 13 PM
> This is how the fire page looks on my macbook screen width... Anyone else have the same?

I think there is an in-between size from mobile to full screen that is not formatted properly, because if I zoom out on my browser it eventually adjusts.

**Comment by carsondrobe** [comment]
Screenshot 2024-04-06 at 2 15 28 PM

Actually this is how it looks on my screen and i think that is pretty good IMO

**Review by carsondrobe — APPROVED** [review]
I am happy with this

**Review by abijeet-dhillon — APPROVED** [review]
LGTM

**Review by robertyac — APPROVED** [review]

**Pull request merged**
