### PR TITLE
Added machine learning predictor and formatted temperature plot

### LINKED ISSUE #152: Connect model to model
This Predictions issue is apart of the list of minimum requirements. This can be split up into smaller issues.

### PR DESCRIPTION
**Pull request by cmcahoon01**
Please make sure it works on mac

### CODE REVIEW

**Comment by cmcahoon01** [comment]
image

**Comment by carsondrobe** [comment]
Now that's a prediction

**Comment by robertyac** [comment]
I committed whatever we had in class for the presentation and I think it messed up the map sizing, Dave will fix her up in his pr then just merge from his pr

**Review by abijeet-dhillon — APPROVED** [review]
Does work good on mine (windows aswell), nice work!

**Review by robertyac — APPROVED** [review]
Awesome everything works I extensively tested the site

**Pull request merged**
