### PR TITLE
Fix fire page

### LINKED ISSUE #244: Fix Fire Page
Restore the fire page to what it was before Saturday.

### PR DESCRIPTION
**Pull request by Davis245**
The fire page has been restored to how is was previously.

Closes #244

### CODE REVIEW

**Review by robertyac — APPROVED** [review]
LGTM

**Comment by Davis245** [comment]
Updated the weather map to be the same size as the fire map. Here's what it looks like.

Screenshot 2024-04-09 at 9 47 31 PM

We can change the bootstrap columns back to 5 and 7 like it was before, but this is 4 and 8 so it is 1/3 and 2/3.

**Comment by carsondrobe** [comment]
Nice looks good yep i think we need this

**Review by robertyac — CHANGES_REQUESTED** [review]
Can you just change the size of the weather map to be bigger? then looks good

**Comment by Davis245** [comment]
Fixed

**Review by abijeet-dhillon — APPROVED** [review]
Awesome, lgtm!

**Review by robertyac — APPROVED** [review]

**Comment by robertyac** [comment]
Looks good!

**Comment by robertyac** [comment]
Fixed the merge conflicts

**Pull request merged**
